micronaut:
  application:
    name: mockbeantest
  server:
    port: 8888
netty:
  default:
    allocator:
      max-order: 3

each-prop:
  test1:
    value: value1
  test2:
    value: value2
  test3:
    value: value3

properties:
  testImpl1:
    value: valueImpl
